name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: timrogers/release-raycast-extension@main
        with:
          extensions_fork: timrogers/extensions
          github_access_token: ${{ secrets.gh_access_token }}
          extension_path: extensions/iata-code-decoder